lart = [
 {'str': '鄧麗欣', 'tag': 'Lo', 'ftok': 3, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 22, 'titlen': 29, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': 'SENZA A Cappella', 'tag': 'Lstr', 'ftok': 11, 'flen': 38, 'slen': 16, 'stopword': False, 'name': False, 'btok': 0, 'blen': 0, 'titlen': 54, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '江海迦', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 15, 'titlen': 22, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '江海迦', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 14, 'titlen': 21, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '江海迦', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 10, 'titlen': 17, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '江海迦', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 9, 'titlen': 16, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '江海迦', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 14, 'titlen': 21, 'bzhtok': 4, '()': False, '《》': False},
 {'str': '劉卓昕', 'tag': 'Lo', 'ftok': 2, 'flen': 11, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 16, 'titlen': 30, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True,'《》': False},
 {'str': '劉卓昕', 'tag': 'Lo', 'ftok': 2, 'flen': 11, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 5, 'blen': 19, 'titlen': 33, 'bzhtok': 1, '《》': False},
 {'str': '劉卓昕', 'tag': 'Lo', 'ftok': 2, 'flen': 11, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 8, 'blen': 42, 'titlen': 56, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True,"''": False},
 {'str': '許志安', 'tag': 'Lo', 'ftok': 2, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 43, 'titlen': 62, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True,'()': False, "''": False},
 {'str': 'Beyond', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 6, 'blen': 10, 'titlen': 16, 'dashbefore': False, 'dashafter': True},
 {'str': 'Beyond', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 8, 'blen': 9, 'titlen': 15, 'dashbefore': False, 'dashafter': True, '（）': False},
 {'str': 'Beyond', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 6, 'blen': 17, 'titlen': 23, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'BOYZ', 'tag': 'Lu', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': False, 'btok': 10, 'blen': 29, 'titlen': 33, '()': False, '[]': False, '《》': False},
 {'str': 'Cassette', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 8, 'stopword': False, 'name': True, 'btok': 9, 'blen': 33, 'titlen': 41, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林欣彤', 'tag': 'Lo', 'ftok': 2, 'flen': 9, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 15, 'titlen': 27, 'bzhtok': 1, '()': False},
 {'str': 'Dear Jane', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 9, 'stopword': False, 'name': True, 'btok': 10, 'blen': 46, 'titlen': 55, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 2, 'flen': 11, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 8, 'titlen': 22, 'bzhtok': 2},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 2, 'flen': 11, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 5, 'blen': 8, 'titlen': 22, 'bzhtok': 2, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 2, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 6, 'titlen': 15, 'bzhtok': 2},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 2, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 8, 'titlen': 17, 'bzhtok': 2, '【】': False},
 {'str': '李幸倪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 8, 'titlen': 19, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '李幸倪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 24, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '李幸倪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 21, 'titlen': 32, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '李幸倪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 13, 'titlen': 24, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 36, 'titlen': 43, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 37, 'titlen': 44, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 32, 'titlen': 39, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 36, 'titlen': 43, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 34, 'titlen': 41, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, '“”': False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 35, 'titlen': 42, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '菊梓喬', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 33, 'titlen': 40, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '何韻詩', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 8, 'titlen': 15, 'bzhtok': 2, '《》': False},
 {'str': '何韻詩', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 25, 'titlen': 32, 'bzhtok': 2, '《》': False},
 {'str': '何韻詩', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 21, 'titlen': 28, 'bzhtok': 2},
 {'str': 'HotCha', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 10, 'blen': 73, 'titlen': 79, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 4, 'flen': 13, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 0, 'blen': 0, 'titlen': 16, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': 'JC', 'tag': 'Lu', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': False, 'btok': 4, 'blen': 26, 'titlen': 28},
 {'str': '麥貝夷', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 11, 'blen': 19, 'titlen': 38, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True,'()': False, '[]': False},
 {'str': '鍾一憲', 'tag': 'Lo', 'ftok': 12, 'flen': 22, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 7, 'blen': 13, 'titlen': 38, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True,'()': False, '[]': False},
 {'str': '張國榮', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 9, 'blen': 18, 'titlen': 37, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': 'Judas', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 5, 'stopword': False, 'name': False, 'btok': 5, 'blen': 10, 'titlen': 15, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 9, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 77, 'titlen': 89, 'bzhtok': 3, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 6, 'flen': 21, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 9, 'blen': 65, 'titlen': 89, 'bzhtok': 2, '《》': False},
 {'str': 'Juno', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': True, 'btok': 4, 'blen': 6, 'titlen': 10},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 19, 'titlen': 27, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 6, 'blen': 7, 'titlen': 27, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 19, 'titlen': 27, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '韋羅莎', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 10, 'titlen': 27, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True,'《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 15, 'titlen': 23, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 15, 'titlen': 23, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 12, 'titlen': 20, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 20, 'blen': 36, 'titlen': 44, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 15, 'flen': 30, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 7, 'blen': 11, 'titlen': 44, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 10, 'titlen': 18, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 15, 'titlen': 23, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '王灝兒', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 26, 'titlen': 32, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '王灝兒', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 33, 'titlen': 39, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '王灝兒', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 27, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '王灝兒', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 28, 'titlen': 34, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '王灝兒', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 27, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 15, 'titlen': 26, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 12, 'titlen': 23, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 10, 'titlen': 21, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 11, 'titlen': 22, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 8, 'titlen': 19, 'bzhtok': 2},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 11, 'titlen': 22, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 5, 'blen': 7, 'titlen': 18, 'bzhtok': 2, '【】': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 7, 'titlen': 18, 'bzhtok': 2},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 5, 'blen': 8, 'titlen': 19, 'bzhtok': 2, '【】': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 8, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 9, 'titlen': 20, 'bzhtok': 2, "''": False},
 {'str': '關楚耀', 'tag': 'Lo', 'ftok': 2, 'flen': 12, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 27, 'titlen': 42, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '古天樂', 'tag': 'Lo', 'ftok': 2, 'flen': 10, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 34, 'titlen': 47, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True,'()': False, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 22, 'titlen': 47, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True,'()': False, '《》': False},
 {'str': 'per se', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 8, 'blen': 22, 'titlen': 28, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳僖儀', 'tag': 'Lo', 'ftok': 11, 'flen': 12, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 13, 'blen': 25, 'titlen': 40, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '陳僖儀', 'tag': 'Lo', 'ftok': 11, 'flen': 12, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 12, 'titlen': 27, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False,'()': False, '[]': False},
 {'str': '陳僖儀', 'tag': 'Lo', 'ftok': 11, 'flen': 12, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 14, 'blen': 25, 'titlen': 40, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': 'Robynn', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': False, 'btok': 11, 'blen': 18, 'titlen': 24, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 1, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'btok': 10, 'blen': 17, 'titlen': 24, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '&', 'tag': 'Po', 'ftok': 2, 'flen': 7, 'slen': 1, 'stopword': False, 'name': False, 'btok': 9, 'blen': 16, 'titlen': 24, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 3, 'flen': 8, 'slen': 1, 'stopword': False, 'name': False, 'btok': 8, 'blen': 15, 'titlen': 24, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Kendy', 'tag': 'Lul', 'ftok': 4, 'flen': 9, 'slen': 5, 'stopword': False, 'name': False, 'btok': 7, 'blen': 10, 'titlen': 24, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Robynn', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': False, 'btok': 11, 'blen': 20, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 1, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'btok': 10, 'blen': 19, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '&', 'tag': 'Po', 'ftok': 2, 'flen': 7, 'slen': 1, 'stopword': False, 'name': False, 'btok': 9, 'blen': 18, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 3, 'flen': 8, 'slen': 1, 'stopword': False, 'name': False, 'btok': 8, 'blen': 17, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Kendy', 'tag': 'Lul', 'ftok': 4, 'flen': 9, 'slen': 5, 'stopword': False, 'name': False, 'btok': 7, 'blen': 12, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Robynn', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': False, 'btok': 11, 'blen': 17, 'titlen': 23, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 1, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'btok': 10, 'blen': 16, 'titlen': 23, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '&', 'tag': 'Po', 'ftok': 2, 'flen': 7, 'slen': 1, 'stopword': False, 'name': False, 'btok': 9, 'blen': 15, 'titlen': 23, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 3, 'flen': 8, 'slen': 1, 'stopword': False, 'name': False, 'btok': 8, 'blen': 14, 'titlen': 23, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Kendy', 'tag': 'Lul', 'ftok': 4, 'flen': 9, 'slen': 5, 'stopword': False, 'name': False, 'btok': 7, 'blen': 9, 'titlen': 23, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Robynn', 'tag': 'Lul', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': False, 'btok': 12, 'blen': 20, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 1, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'btok': 11, 'blen': 19, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '&', 'tag': 'Po', 'ftok': 2, 'flen': 7, 'slen': 1, 'stopword': False, 'name': False, 'btok': 10, 'blen': 18, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 3, 'flen': 8, 'slen': 1, 'stopword': False, 'name': False, 'btok': 9, 'blen': 17, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'Kendy', 'tag': 'Lul', 'ftok': 4, 'flen': 9, 'slen': 5, 'stopword': False, 'name': False, 'btok': 8, 'blen': 12, 'titlen': 26, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '連詩雅', 'tag': 'Lo', 'ftok': 2, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 29, 'titlen': 38, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳僖儀', 'tag': 'Lo', 'ftok': 2, 'flen': 10, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 8, 'titlen': 21, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '鄧麗欣', 'tag': 'Lo', 'ftok': 2, 'flen': 12, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 21, 'titlen': 36, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True,'()': False},
 {'str': 'ToNick', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 16, 'blen': 34, 'titlen': 40, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': 'ToNick', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'btok': 16, 'blen': 36, 'titlen': 42, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': 'U', 'tag': 'Lu', 'ftok': 0, 'flen': 0, 'slen': 1, 'stopword': False, 'name': False, 'btok': 7, 'blen': 12, 'titlen': 13, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '記仝人', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 9, 'titlen': 13, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': 'U', 'tag': 'Lu', 'ftok': 0, 'flen': 0, 'slen': 1, 'stopword': False, 'name': False, 'btok': 8, 'blen': 13, 'titlen': 14, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '記歌手', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 7, 'blen': 10, 'titlen': 14, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '丁可欣', 'tag': 'Lo', 'ftok': 2, 'flen': 9, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 5, 'blen': 30, 'titlen': 42, 'bzhtok': 2, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 19, 'flen': 28, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 5, 'btok': 1, 'blen': 4, 'titlen': 35, 'bzhtok': 1, '《》': False},
 {'str': '側田', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 40, 'titlen': 42, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '側田', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 36, 'titlen': 38, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '傅又宣', 'tag': 'Lo', 'ftok': 3, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 43, 'titlen': 51, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': True, '《》': False},
 {'str': '傅又宣', 'tag': 'Lo', 'ftok': 3, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 9, 'blen': 31, 'titlen': 39, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': True, '《》': False},
 {'str': 'KOLOR', 'tag': 'Lu', 'ftok': 2, 'flen': 3, 'slen': 5, 'stopword': False, 'name': True, 'btok': 2, 'blen': 21, 'titlen': 29, 'dashbefore': True, 'dashafter': True},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 3, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 6, 'blen': 27, 'titlen': 35, 'bzhtok': 2, '《》': False, '【】': False},
 {'str': '劉德華', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 17, 'blen': 52, 'titlen': 55, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True},
 {'str': '吳倩蓮', 'tag': 'Lo', 'ftok': 4, 'flen': 13, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 13, 'blen': 39, 'titlen': 55, 'bzhtok': 4, 'dashbefore': True, 'dashafter': True},
 {'str': '袁鳳瑛', 'tag': 'Lo', 'ftok': 12, 'flen': 27, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 5, 'blen': 25, 'titlen': 55, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '劉浩龍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 2, 'blen': 5, 'titlen': 8, 'bzhtok': 2},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 14, 'flen': 21, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 1, 'blen': 4, 'titlen': 28, 'bzhtok': 1, '《》': False},
 {'str': '何韻詩', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 12, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '古巨基', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 35, 'titlen': 38, 'bzhtok': 3, '[]': False, '《》': False},
 {'str': '黃子華', 'tag': 'Lo', 'ftok': 5, 'flen': 17, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 6, 'blen': 18, 'titlen': 38, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '古巨基', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 60, 'titlen': 63, 'bzhtok': 4, '()': False, '[]': False, '《》': False},
 {'str': '胡定欣', 'tag': 'Lo', 'ftok': 16, 'flen': 60, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 0, 'blen': 0, 'titlen': 63, 'bzhtok': 1, '()': False, '[]': False, '《》': False},
 {'str': '古巨基', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 41, 'titlen': 44, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '古巨基', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 21, 'blen': 72, 'titlen': 75, 'bzhtok': 4, '()': False, '[]': False, '《》': False},
 {'str': '胡定欣', 'tag': 'Lo', 'ftok': 6, 'flen': 13, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 15, 'blen': 59, 'titlen': 75, 'bzhtok': 3, '()': False, '[]': False, '《》': False},
 {'str': '古巨基', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 16, 'titlen': 19, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 6, 'blen': 37, 'titlen': 56, 'bzhtok': 1, '[]': False, '《》': False},
 {'str': '吳嘉熙', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 15, 'blen': 26, 'titlen': 29, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False, '《》': False},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 37, 'titlen': 40, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 35, 'titlen': 38, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 28, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 38, 'titlen': 41, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 19, 'blen': 49, 'titlen': 52, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '田蕊妮', 'tag': 'Lo', 'ftok': 12, 'flen': 28, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 7, 'blen': 21, 'titlen': 52, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 34, 'titlen': 37, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 35, 'titlen': 38, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 34, 'titlen': 37, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 33, 'titlen': 36, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 35, 'titlen': 38, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '吳浩康', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 25, 'blen': 63, 'titlen': 66, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False, '《》': False},
 {'str': '吳浩康', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 30, 'titlen': 33, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '吳若希', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 37, 'titlen': 40, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '吳若希', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 40, 'titlen': 43, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '吳若希', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 42, 'titlen': 45, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '吳雨霏', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 50, 'titlen': 53, 'bzhtok': 3, '()': False, '《》': False},
 {'str': '吳雨霏', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 15, 'titlen': 18, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '吳雨霏', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 29, 'titlen': 32, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '吳雨霏', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 21, 'titlen': 24, 'bzhtok': 3, '《》': False},
 {'str': '吳雨霏', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 7, 'titlen': 10, 'bzhtok': 2, '《》': False},
 {'str': '周柏豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 55, 'titlen': 58, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '周柏豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 23, 'titlen': 26, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '周柏豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 47, 'titlen': 50, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '楊千嬅', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 8, 'blen': 35, 'titlen': 50, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '周柏豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 34, 'titlen': 37, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '周柏豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 28, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '周柏豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 28, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '孩子問', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 6, 'titlen': 9, 'bzhtok': 2},
 {'str': '孫耀威', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 41, 'titlen': 44, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '周國賢', 'tag': 'Lo', 'ftok': 7, 'flen': 20, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 8, 'blen': 33, 'titlen': 56, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '【】': False},
 {'str': '周國賢', 'tag': 'Lo', 'ftok': 16, 'flen': 35, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 8, 'blen': 33, 'titlen': 71, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False,'()': False, '【】': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 13, 'blen': 24, 'titlen': 43, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False,'()': False, '[]': False},
 {'str': '陳詩慧', 'tag': 'Lo', 'ftok': 10, 'flen': 24, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 8, 'blen': 11, 'titlen': 38, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False,'[]': False, "''": False},
 {'str': '古巨基', 'tag': 'Lo', 'ftok': 8, 'flen': 18, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 9, 'titlen': 30, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '薛凱琪', 'tag': 'Lo', 'ftok': 8, 'flen': 14, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 12, 'titlen': 29, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '關淑怡', 'tag': 'Lo', 'ftok': 8, 'flen': 15, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 14, 'titlen': 32, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '鍾嘉欣', 'tag': 'Lo', 'ftok': 8, 'flen': 14, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 12, 'blen': 28, 'titlen': 45, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False,'()': False, '[]': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 8, 'flen': 15, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 11, 'titlen': 29, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '敖嘉年', 'tag': 'Lo', 'ftok': 8, 'flen': 15, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 14, 'titlen': 32, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '吳若希', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 14, 'titlen': 33, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '鄭俊弘', 'tag': 'Lo', 'ftok': 8, 'flen': 14, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 13, 'titlen': 30, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '鍾嘉欣', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 13, 'titlen': 32, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '薛凱琪', 'tag': 'Lo', 'ftok': 8, 'flen': 15, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 13, 'titlen': 31, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 8, 'flen': 15, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 13, 'titlen': 31, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '許志安', 'tag': 'Lo', 'ftok': 8, 'flen': 17, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 11, 'titlen': 31, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 8, 'flen': 14, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 9, 'blen': 24, 'titlen': 41, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 10, 'flen': 18, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 7, 'blen': 20, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False,'()': False, '[]': False},
 {'str': '吳若希', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 11, 'titlen': 30, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '馬浚偉', 'tag': 'Lo', 'ftok': 12, 'flen': 19, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 10, 'blen': 17, 'titlen': 39, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '鍾嘉欣', 'tag': 'Lo', 'ftok': 14, 'flen': 23, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 5, 'btok': 8, 'blen': 13, 'titlen': 39, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False,'[]': False},
 {'str': '林峯', 'tag': 'Lo', 'ftok': 12, 'flen': 20, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 8, 'blen': 13, 'titlen': 35, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 12, 'flen': 20, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 4, 'blen': 11, 'titlen': 34, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False,'()': False, '[]': False},
 {'str': '許廷鏗', 'tag': 'Lo', 'ftok': 8, 'flen': 13, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 13, 'titlen': 29, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '許廷鏗', 'tag': 'Lo', 'ftok': 8, 'flen': 13, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 8, 'blen': 13, 'titlen': 29, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '許廷鏗', 'tag': 'Lo', 'ftok': 8, 'flen': 14, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 13, 'titlen': 30, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '陳豪', 'tag': 'Lo', 'ftok': 8, 'flen': 21, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 10, 'blen': 18, 'titlen': 41, 'bzhtok': 5, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '林保怡', 'tag': 'Lo', 'ftok': 10, 'flen': 24, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 8, 'blen': 14, 'titlen': 41, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False,'[]': False},
 {'str': '黃德斌', 'tag': 'Lo', 'ftok': 12, 'flen': 28, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 5, 'btok': 6, 'blen': 10, 'titlen': 41, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 26, 'titlen': 29, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 48, 'titlen': 51, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 29, 'titlen': 32, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 28, 'titlen': 31, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 17, 'blen': 43, 'titlen': 46, 'bzhtok': 3, '()': False, '[]': False, '《》': False,'“”': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 51, 'titlen': 54, 'bzhtok': 5, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 47, 'titlen': 54, 'bzhtok': 4, '《》': False},
 {'str': '專家', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 7, 'blen': 26, 'titlen': 28, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': 'Dickson', 'tag': 'Lul', 'ftok': 1, 'flen': 2, 'slen': 7, 'stopword': False, 'name': True, 'btok': 6, 'blen': 19, 'titlen': 28, 'dashbefore': False, 'dashafter': True},
 {'str': '小塵埃', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 33, 'titlen': 36, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '小塵埃', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 30, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '小塵埃', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 31, 'titlen': 34, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '小塵埃', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '小肥', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 19, 'titlen': 21, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True},
 {'str': '岑寧兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 29, 'titlen': 32, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True},
 {'str': '岑寧兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 30, 'titlen': 33, 'bzhtok': 3, '《》': False},
 {'str': '布志綸', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 50, 'titlen': 53, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張國榮', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 43, 'titlen': 46, 'bzhtok': 2, '【】': False},
 {'str': '張國榮', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 5, 'blen': 7, 'titlen': 10, 'bzhtok': 3, '（）': False},
 {'str': '張學友', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 27, 'titlen': 30, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張學友', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 13, 'titlen': 16, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張學友', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 12, 'titlen': 15, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張學友', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 10, 'titlen': 13, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 22, 'blen': 65, 'titlen': 68, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 31, 'titlen': 34, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 30, 'titlen': 33, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 34, 'titlen': 37, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 32, 'titlen': 35, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 15, 'blen': 50, 'titlen': 53, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 56, 'titlen': 59, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 61, 'titlen': 64, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '容祖兒', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 43, 'titlen': 64, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 35, 'titlen': 38, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 46, 'titlen': 49, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 47, 'titlen': 50, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 31, 'titlen': 34, 'bzhtok': 2, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 45, 'titlen': 48, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 29, 'titlen': 32, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 38, 'titlen': 41, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 24, 'blen': 73, 'titlen': 76, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '王菀之', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 18, 'blen': 55, 'titlen': 76, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 62, 'titlen': 65, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '王菀之', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 44, 'titlen': 65, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 28, 'titlen': 31, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 31, 'titlen': 34, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 46, 'titlen': 49, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 46, 'titlen': 49, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 28, 'titlen': 31, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 47, 'titlen': 50, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 29, 'titlen': 32, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 49, 'titlen': 52, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 45, 'titlen': 48, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 45, 'titlen': 48, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 45, 'titlen': 48, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 47, 'titlen': 50, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 31, 'titlen': 34, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 30, 'titlen': 33, 'bzhtok': 2},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 23, 'titlen': 26, 'bzhtok': 3},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 23, 'titlen': 26, 'bzhtok': 3},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 22, 'titlen': 25, 'bzhtok': 3},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 8, 'titlen': 11, 'bzhtok': 2},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 4, 'titlen': 7, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '徐加晴', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 38, 'titlen': 41, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '恆仔', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 33, 'titlen': 35, 'bzhtok': 5, '《》': False, '【】': False},
 {'str': '譚杏藍', 'tag': 'Lo', 'ftok': 4, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 9, 'blen': 27, 'titlen': 35, 'bzhtok': 4, '《》': False, '【】': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 2, 'blen': 9, 'titlen': 18, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 2, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 10, 'titlen': 19, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 0, 'blen': 0, 'titlen': 19, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 5, 'flen': 22, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 6, 'blen': 37, 'titlen': 62, 'bzhtok': 1, '[]': False, '《》': False},
 {'str': '戴祖儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 28, 'titlen': 31, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 9, 'blen': 26, 'titlen': 36, 'bzhtok': 2, '()': False, '[]': False, '【】': False},
 {'str': '新青年理髮廳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 6, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 11, 'titlen': 17, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '方皓玟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 34, 'titlen': 37, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '方皓玟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 37, 'titlen': 40, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '方皓玟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 33, 'titlen': 36, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '方皓玟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 29, 'titlen': 32, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '方皓玟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 27, 'titlen': 30, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '曾樂彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 41, 'titlen': 44, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '曾樂彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 29, 'titlen': 32, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '曾樂彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 33, 'titlen': 36, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '曾樂彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 19, 'blen': 73, 'titlen': 76, 'bzhtok': 3, '()': False, '[]': False, '《》': False},
 {'str': '李克勤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 29, 'titlen': 32, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '李晧軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 38, 'titlen': 41, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True},
 {'str': '李靖筠', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 30, 'titlen': 33, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '林二汶', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 21, 'titlen': 24, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '林奕匡', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 30, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林奕匡', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 30, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林奕匡', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 22, 'titlen': 25, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林子祥', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 35, 'titlen': 38, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '林家謙', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 50, 'titlen': 53, 'bzhtok': 1, '()': False, '《》': False},
 {'str': '林家謙', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 51, 'titlen': 54, 'bzhtok': 2, '()': False, '《》': False},
 {'str': '林家謙', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 48, 'titlen': 51, 'bzhtok': 2, '()': False, '《》': False},
 {'str': '林憶蓮', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 10, 'titlen': 13, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '林欣彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 42, 'titlen': 45, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林欣彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 41, 'titlen': 44, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林欣彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 59, 'titlen': 62, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林欣彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 26, 'titlen': 29, 'bzhtok': 2, '()': False},
 {'str': '林欣彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林海峰', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 49, 'titlen': 52, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林海峰', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 35, 'titlen': 38, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '林穎彤', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 27, 'titlen': 30, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '梁詠琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 23, 'titlen': 26, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '梁釗峰', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 37, 'titlen': 40, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '梁釗峰', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 41, 'titlen': 44, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '梁釗峰', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 38, 'titlen': 41, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '梅艷芳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 45, 'titlen': 48, 'bzhtok': 4, '[]': False},
 {'str': '梅艷芳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 2, 'blen': 5, 'titlen': 8, 'bzhtok': 2},
 {'str': '楊千嬅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 16, 'blen': 44, 'titlen': 47, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '楊思琦', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 28, 'bzhtok': 2, '[]': False},
 {'str': '何韻詩', 'tag': 'Lo', 'ftok': 3, 'flen': 5, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 9, 'blen': 27, 'titlen': 35, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True, '《》': False, '“”': False, "''": False},
 {'str': '周國賢', 'tag': 'Lo', 'ftok': 9, 'flen': 23, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 6, 'blen': 11, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '【】': False},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 2, 'blen': 5, 'titlen': 15, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '沈震軒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 43, 'titlen': 46, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '泳兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 27, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '泳兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 27, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '泳兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 27, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '泳兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 24, 'titlen': 26, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '洪卓立', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 27, 'titlen': 30, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '洪卓立', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 46, 'titlen': 49, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '洪卓立', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 28, 'titlen': 31, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '洪卓立', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 28, 'titlen': 31, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '洪嘉豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 15, 'blen': 56, 'titlen': 59, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '洪嘉豪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 52, 'titlen': 55, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '關正傑', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 10, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 39, 'titlen': 49, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '吳業坤', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 12, 'blen': 37, 'titlen': 47, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '王菀之', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 32, 'titlen': 35, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '周國賢', 'tag': 'Lo', 'ftok': 11, 'flen': 17, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 4, 'btok': 0, 'blen': 0, 'titlen': 20, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '符家浚', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 20, 'blen': 37, 'titlen': 40, 'bzhtok': 6, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '簡淑兒', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 15, 'blen': 43, 'titlen': 46, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '楊千嬅', 'tag': 'Lo', 'ftok': 8, 'flen': 9, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 8, 'blen': 17, 'titlen': 29, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '胡琳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 35, 'titlen': 37, 'bzhtok': 2, '()': False},
 {'str': '胡琳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 39, 'titlen': 41, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '胡琳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 45, 'titlen': 47, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, '“”': False, "''": False},
 {'str': '胡鴻鈞', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 28, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '胡鴻鈞', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 52, 'titlen': 55, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '胡鴻鈞', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 43, 'titlen': 46, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '莫文蔚', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 18, 'titlen': 21, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '蔚雨芯', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 29, 'titlen': 32, 'bzhtok': 2, '《》': False},
 {'str': '蘇永康', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 21, 'titlen': 24, 'bzhtok': 3, '《》': False},
 {'str': '蘇永康', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 35, 'titlen': 38, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 11, 'blen': 31, 'titlen': 38, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '衛蘭', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 67, 'titlen': 69, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '衛蘭', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 65, 'titlen': 67, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '衛蘭', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 52, 'titlen': 54, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '許廷鏗', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 55, 'titlen': 58, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '許廷鏗', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 50, 'titlen': 53, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '許志安', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 40, 'titlen': 43, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '許靖韻', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 13, 'blen': 50, 'titlen': 53, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 17, 'titlen': 20, 'bzhtok': 2, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 28, 'titlen': 31, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 19, 'titlen': 22, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False, '（）': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 26, 'titlen': 29, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 42, 'titlen': 45, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 33, 'titlen': 36, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 31, 'titlen': 34, 'bzhtok': 2, '()': False, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 6, 'titlen': 9, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 8, 'titlen': 11, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 39, 'titlen': 42, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '譚嘉儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 59, 'titlen': 62, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '譚嘉儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 48, 'titlen': 51, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '譚嘉儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 41, 'titlen': 44, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '譚嘉儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 23, 'titlen': 26, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '譚嘉儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 27, 'titlen': 30, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '譚嘉儀', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 19, 'blen': 40, 'titlen': 43, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '譚杏藍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 15, 'blen': 36, 'titlen': 39, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '趙學而', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 20, 'blen': 50, 'titlen': 53, 'bzhtok': 6, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '趙慧珊', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 32, 'titlen': 35, 'bzhtok': 2, '《》': False},
 {'str': '岑寧兒', 'tag': 'Lo', 'ftok': 16, 'flen': 29, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 5, 'btok': 1, 'blen': 1, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': True, '《》': False},
 {'str': '農夫', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 30, 'titlen': 32, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': 'RubberBand', 'tag': 'Lstr', 'ftok': 13, 'flen': 38, 'slen': 10, 'stopword': False, 'name': True, 'btok': 5, 'blen': 11, 'titlen': 59, '《》': False, '【】': False},
 {'str': '連詩雅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 48, 'titlen': 51, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '連詩雅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 44, 'titlen': 47, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '連詩雅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 40, 'titlen': 43, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '達明一派', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 5, 'blen': 10, 'titlen': 14, 'bzhtok': 3, '《》': False},
 {'str': '達明一派', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 2, 'blen': 4, 'titlen': 8, 'bzhtok': 2},
 {'str': '鄧小巧', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 41, 'titlen': 44, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄧小巧', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄧小巧', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 41, 'titlen': 44, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄧月平', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 8, 'blen': 28, 'titlen': 31, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '鄧麗欣', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 29, 'titlen': 32, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄧麗欣', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 30, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '鄧麗欣', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 13, 'titlen': 16, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄭中基', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 9, 'titlen': 12, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '鄭中基', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 16, 'titlen': 20, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': True},
 {'str': '鄭欣宜', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 29, 'titlen': 32, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '鄭欣宜', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 28, 'titlen': 31, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '鄭秀文', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 34, 'titlen': 37, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄭秀文', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 64, 'titlen': 67, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '鄭融', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 45, 'titlen': 47, 'bzhtok': 2, '《》': False},
 {'str': '鄭融', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 41, 'titlen': 43, 'bzhtok': 2, '《》': False},
 {'str': '鍾一憲', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 14, 'titlen': 17, 'bzhtok': 3, '《》': False},
 {'str': '麥貝夷', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 8, 'titlen': 17, 'bzhtok': 2, '《》': False},
 {'str': '鍾一憲', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 14, 'titlen': 17, 'bzhtok': 3, '《》': False},
 {'str': '麥貝夷', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 8, 'titlen': 17, 'bzhtok': 2, '《》': False},
 {'str': '陈奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 3, 'titlen': 6, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '陳健安', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 39, 'titlen': 42, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳健安', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 43, 'titlen': 46, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳健安', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 35, 'titlen': 38, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 19, 'titlen': 22, 'bzhtok': 2, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 31, 'titlen': 34, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 24, 'titlen': 27, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 11, 'blen': 32, 'titlen': 35, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 14, 'blen': 61, 'titlen': 64, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 24, 'blen': 68, 'titlen': 71, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False, "''": False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 21, 'titlen': 24, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 7, 'titlen': 10, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 13, 'titlen': 16, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 19, 'titlen': 22, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 6, 'titlen': 9, 'bzhtok': 2, '【】': False},
 {'str': '陳慧琳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 38, 'titlen': 41, 'bzhtok': 1, '[]': False, '《》': False},
 {'str': '陳慧琳', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 38, 'titlen': 41, 'bzhtok': 2, '[]': False, '《》': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 53, 'titlen': 56, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 25, 'titlen': 28, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 16, 'titlen': 19, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 30, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 16, 'titlen': 19, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 32, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳柏宇', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 5, 'titlen': 8, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '陳百強', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 11, 'titlen': 14, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳百強', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 8, 'blen': 11, 'titlen': 14, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '陳蕾', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 7, 'blen': 45, 'titlen': 47, 'bzhtok': 2, '《》': False},
 {'str': '陳詠謙', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 49, 'titlen': 52, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '音樂份子', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 3, 'blen': 9, 'titlen': 13, 'bzhtok': 2, '《》': False},
 {'str': '顏卓靈', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 35, 'titlen': 38, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '馮允謙', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 38, 'titlen': 41, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '麥家瑜', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 21, 'titlen': 24, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 18, 'blen': 55, 'titlen': 58, 'bzhtok': 5, '[]': False, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 4, 'flen': 11, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 14, 'blen': 44, 'titlen': 58, 'bzhtok': 4, '[]': False, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 26, 'blen': 49, 'titlen': 52, 'bzhtok': 8, '()': False, '《》': False, '（）': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 18, 'flen': 33, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 7, 'btok': 8, 'blen': 16, 'titlen': 52, 'bzhtok': 2, '()': True, '《》': False, '（）': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 9, 'blen': 20, 'titlen': 23, 'bzhtok': 5, '《》': False},
 {'str': '謝安琪', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 4, 'blen': 10, 'titlen': 23, 'bzhtok': 3, '《》': False},
 {'str': '麥浚龍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 4, 'blen': 6, 'titlen': 9, 'bzhtok': 2, '《》': False},
 {'str': '黃妍', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 35, 'titlen': 37, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黃淑蔓', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 44, 'titlen': 47, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黃淑蔓', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 42, 'titlen': 45, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黃淑蔓', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 34, 'titlen': 37, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黃淑蔓', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 38, 'titlen': 41, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黃淑蔓', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 42, 'titlen': 45, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黃秋生', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 6, 'blen': 14, 'titlen': 17, 'bzhtok': 4},
 {'str': '張敬軒', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 10, 'titlen': 17, 'bzhtok': 3},
 {'str': '黎曉陽', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 10, 'blen': 30, 'titlen': 33, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': '黎瑞恩', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 44, 'titlen': 47, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '黎瑞恩', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 1, 'btok': 12, 'blen': 38, 'titlen': 41, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '陳奕迅', 'tag': 'Lo', 'ftok': 5, 'flen': 13, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 6, 'blen': 37, 'titlen': 53, 'bzhtok': 1, '[]': False, '《》': False}
]

