ltit = [
 {'str': '電燈膽', 'tag': 'Lo', 'ftok': 9, 'flen': 17, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 9, 'titlen': 29, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '串燒廣東歌', 'tag': 'Lo', 'ftok': 1, 'flen': 4, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 10, 'blen': 45, 'titlen': 54, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False},
 {'str': 'Everyday', 'tag': 'Lul', 'ftok': 7, 'flen': 11, 'slen': 8, 'stopword': False, 'name': False, 'btok': 2, 'blen': 3, 'titlen': 22, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': 'Tonight', 'tag': 'Lul', 'ftok': 7, 'flen': 11, 'slen': 7, 'stopword': False, 'name': False, 'btok': 2, 'blen': 3, 'titlen': 21, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '小問題', 'tag': 'Lo', 'ftok': 7, 'flen': 11, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 17, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '無期', 'tag': 'Lo', 'ftok': 7, 'flen': 11, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 16, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '自由', 'tag': 'Lo', 'ftok': 5, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 10, 'titlen': 21, 'bzhtok': 3, '()': False, '《》': True},
 {'str': 'Hallelujah', 'tag': 'Lul', 'ftok': 5, 'flen': 16, 'slen': 10, 'stopword': False, 'name': False, 'btok': 3, 'blen': 4, 'titlen': 30, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': 'Nella Fantasia', 'tag': 'Lstr', 'ftok': 5, 'flen': 16, 'slen': 14, 'stopword': False, 'name': False, 'btok': 2, 'blen': 3, 'titlen': 33, '《》': True},
 {'str': 'Think of Me from', 'tag': 'Lstr', 'ftok': 6, 'flen': 17, 'slen': 16, 'stopword': False, 'name': False, 'btok': 4, 'blen': 23, 'titlen': 56, 'dashbefore': True, 'dashafter': False, "''": False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 7, 'flen': 33, 'slen': 1, 'stopword': False, 'name': False, 'btok': 3, 'blen': 22, 'titlen': 56, 'dashbefore': True, 'dashafter': False, "''": False},
 {'str': "'", 'tag': 'Po', 'ftok': 8, 'flen': 34, 'slen': 1, 'stopword': False, 'name': False, 'btok': 2, 'blen': 21, 'titlen': 56, 'dashbefore': True, 'dashafter': False, "''": False},
 {'str': 'Phantom of the Opera', 'tag': 'Lstr', 'ftok': 9, 'flen': 35, 'slen': 20, 'stopword': False, 'name': False, 'btok': 1, 'blen': 1, 'titlen': 56, 'dashbefore': True, 'dashafter': False, "''": True},
 {'str': "'", 'tag': 'Po', 'ftok': 10, 'flen': 55, 'slen': 1, 'stopword': False, 'name': False, 'btok': 0, 'blen': 0, 'titlen': 56, 'dashbefore': True, 'dashafter': False, "''": False},
 {'str': 'Remember Me', 'tag': 'Lstr', 'ftok': 6, 'flen': 22, 'slen': 11, 'stopword': False, 'name': False, 'btok': 10, 'blen': 29, 'titlen': 62, 'dashbefore': True, 'dashafter': True, '()': False, "''": False},
 {'str': '光輝歲月', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 0, 'blen': 0, 'titlen': 16, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '情人', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 4, 'blen': 4, 'titlen': 15, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '（）': False},
 {'str': '長城', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 12, 'titlen': 23, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '大男孩', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 8, 'blen': 25, 'titlen': 33, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '某日', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': 'Da Di Da', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 8, 'stopword': False, 'name': False, 'btok': 6, 'blen': 19, 'titlen': 27, '()': False},
 {'str': '經過一些秋與冬', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 36, 'titlen': 55, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '七百年後', 'tag': 'Lo', 'ftok': 4, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 22, 'bzhtok': 1},
 {'str': '陀飛輪', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 22, 'bzhtok': 1, '《》': True},
 {'str': '沙龍', 'tag': 'Lo', 'ftok': 4, 'flen': 10, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 15, 'bzhtok': 1},
 {'str': '無人之境', 'tag': 'Lo', 'ftok': 4, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 17, 'bzhtok': 1, '【】': True},
 {'str': '信', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 1, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 19, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '天地一沙鷗', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 15, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '很堅強', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 32, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '自我感覺還好', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 24, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '但願人長久', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 28, 'titlen': 43, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '你就是天下', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 29, 'titlen': 44, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '別再怕', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 26, 'titlen': 39, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '從未說起', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 29, 'titlen': 43, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '心有不甘', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 27, 'titlen': 41, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, '“”': False},
 {'str': '聽雪落淚', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 28, 'titlen': 42, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '鋼鐵有淚', 'tag': 'Lo', 'ftok': 5, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 26, 'titlen': 40, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '代你白頭', 'tag': 'Lo', 'ftok': 3, 'flen': 8, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 15, 'bzhtok': 1, '《》': True},
 {'str': '極夜後', 'tag': 'Lo', 'ftok': 3, 'flen': 8, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 32, 'bzhtok': 1, '《》': True},
 {'str': '鋼鐵是怎樣煉成的', 'tag': 'Lo', 'ftok': 3, 'flen': 8, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 28, 'bzhtok': 1},
 {'str': 'Are You Still My Best Friend', 'tag': 'Lstr', 'ftok': 4, 'flen': 9, 'slen': 28, 'stopword': False, 'name': False, 'btok': 6, 'blen': 42, 'titlen': 79, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '花與琴的流星', 'tag': 'Lo', 'ftok': 6, 'flen': 9, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 13, 'titlen': 28, 'bzhtok': 3, '()': False, '[]': False},
 {'str': 'I Miss You', 'tag': 'Lstr', 'ftok': 0, 'flen': 0, 'slen': 10, 'stopword': False, 'name': False, 'btok': 4, 'blen': 6, 'titlen': 16, 'dashbefore': False, 'dashafter': True},
 {'str': '別𠱁我', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 22, 'titlen': 28, 'bzhtok': 1},
 {'str': '犯眾憎', 'tag': 'Lo', 'ftok': 16, 'flen': 28, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 3, 'blen': 7, 'titlen': 38, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '有心人', 'tag': 'Lo', 'ftok': 12, 'flen': 22, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 5, 'blen': 12, 'titlen': 37, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '()': False, '[]': False},
 {'str': '一線之差', 'tag': 'Lo', 'ftok': 2, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 3, 'blen': 5, 'titlen': 15, 'bzhtok': 2, '《》': True},
 {'str': '廢話', 'tag': 'Lo', 'ftok': 13, 'flen': 49, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 38, 'titlen': 89, 'bzhtok': 1, '《》': True},
 {'str': '借火', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 3, 'titlen': 10, 'bzhtok': 1},
 {'str': '廢話', 'tag': 'Lo', 'ftok': 11, 'flen': 24, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 1, 'blen': 1, 'titlen': 27, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '黑盒', 'tag': 'Lo', 'ftok': 11, 'flen': 21, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 3, 'blen': 4, 'titlen': 27, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '勇悍', 'tag': 'Lo', 'ftok': 7, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 9, 'titlen': 23, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 8, 'flen': 14, 'slen': 1, 'stopword': False, 'name': False, 'btok': 6, 'blen': 8, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '·', 'tag': 'Po', 'ftok': 9, 'flen': 15, 'slen': 1, 'stopword': False, 'name': False, 'btok': 5, 'blen': 7, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 10, 'flen': 16, 'slen': 1, 'stopword': False, 'name': False, 'btok': 4, 'blen': 6, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '17', 'tag': 'Nd', 'ftok': 11, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'btok': 3, 'blen': 4, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '困獸', 'tag': 'Lo', 'ftok': 7, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 9, 'titlen': 23, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 8, 'flen': 14, 'slen': 1, 'stopword': False, 'name': False, 'btok': 6, 'blen': 8, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '·', 'tag': 'Po', 'ftok': 9, 'flen': 15, 'slen': 1, 'stopword': False, 'name': False, 'btok': 5, 'blen': 7, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 10, 'flen': 16, 'slen': 1, 'stopword': False, 'name': False, 'btok': 4, 'blen': 6, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '28', 'tag': 'Nd', 'ftok': 11, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'btok': 3, 'blen': 4, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '寂寞就如', 'tag': 'Lo', 'ftok': 7, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 4, 'titlen': 20, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '寂寞就如', 'tag': 'Lo', 'ftok': 6, 'flen': 11, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 16, 'blen': 29, 'titlen': 44, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True, '《》': True},
 {'str': '其實寂寞', 'tag': 'Lo', 'ftok': 20, 'flen': 37, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 2, 'blen': 3, 'titlen': 44, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '情感的廢墟', 'tag': 'Lo', 'ftok': 7, 'flen': 12, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 1, 'blen': 1, 'titlen': 18, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '暴烈', 'tag': 'Lo', 'ftok': 7, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 9, 'titlen': 23, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 8, 'flen': 14, 'slen': 1, 'stopword': False, 'name': False, 'btok': 6, 'blen': 8, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '·', 'tag': 'Po', 'ftok': 9, 'flen': 15, 'slen': 1, 'stopword': False, 'name': False, 'btok': 5, 'blen': 7, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 10, 'flen': 16, 'slen': 1, 'stopword': False, 'name': False, 'btok': 4, 'blen': 6, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '34', 'tag': 'Nd', 'ftok': 11, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'btok': 3, 'blen': 4, 'titlen': 23, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '主宰', 'tag': 'Lo', 'ftok': 6, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 32, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '你帶著我的青春離去', 'tag': 'Lo', 'ftok': 6, 'flen': 9, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 39, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '揮揮手', 'tag': 'Lo', 'ftok': 6, 'flen': 9, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '維多利亞', 'tag': 'Lo', 'ftok': 6, 'flen': 9, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 34, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '逃生門', 'tag': 'Lo', 'ftok': 6, 'flen': 9, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '一個女人和浴室', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 4, 'titlen': 26, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '人妻的偽術', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 23, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '偷情的禮儀', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 1, 'blen': 1, 'titlen': 21, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '其實寂寞', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 22, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '年度之歌', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 19, 'bzhtok': 1},
 {'str': '沐春風', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 4, 'titlen': 22, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '活著', 'tag': 'Lo', 'ftok': 5, 'flen': 13, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 18, 'bzhtok': 1, '【】': True},
 {'str': '祝英台', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 18, 'bzhtok': 1},
 {'str': '載我走', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 4, 'titlen': 19, 'bzhtok': 1, '【】': True},
 {'str': '鍾無艷', 'tag': 'Lo', 'ftok': 5, 'flen': 13, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 4, 'titlen': 20, 'bzhtok': 1, "''": True},
 {'str': '写真家', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 42, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '一個男人', 'tag': 'Lo', 'ftok': 11, 'flen': 30, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 7, 'blen': 13, 'titlen': 47, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 13, 'flen': 35, 'slen': 1, 'stopword': False, 'name': False, 'btok': 5, 'blen': 11, 'titlen': 47, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': '一個女人', 'tag': 'Lo', 'ftok': 14, 'flen': 36, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 4, 'blen': 7, 'titlen': 47, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 15, 'flen': 40, 'slen': 1, 'stopword': False, 'name': False, 'btok': 3, 'blen': 6, 'titlen': 47, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': '和浴室', 'tag': 'Lo', 'ftok': 16, 'flen': 41, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 5, 'btok': 2, 'blen': 3, 'titlen': 47, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': '天空塌下前', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 4, 'blen': 14, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '後備', 'tag': 'Lo', 'ftok': 9, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 15, 'blen': 29, 'titlen': 40, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '忘川', 'tag': 'Lo', 'ftok': 9, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 16, 'titlen': 27, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '蜚蜚', 'tag': 'Lo', 'ftok': 9, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 16, 'blen': 29, 'titlen': 40, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': 'One', 'tag': 'Lul', 'ftok': 9, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'btok': 2, 'blen': 3, 'titlen': 24, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '未來紀念館', 'tag': 'Lo', 'ftok': 9, 'flen': 18, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 3, 'titlen': 26, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '荷光', 'tag': 'Lo', 'ftok': 9, 'flen': 18, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 2, 'blen': 3, 'titlen': 23, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '青春終老', 'tag': 'Lo', 'ftok': 9, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 3, 'blen': 4, 'titlen': 26, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '過路人', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '忘川', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 21, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '不要離我太遠', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 12, 'titlen': 36, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '你好', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 12, 'blen': 29, 'titlen': 40, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '長相廝守', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 12, 'blen': 29, 'titlen': 42, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '我做你', 'tag': 'Lo', 'ftok': 5, 'flen': 7, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 13, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '你做我', 'tag': 'Lo', 'ftok': 6, 'flen': 8, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 14, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '剩下我的回憶裡', 'tag': 'Lo', 'ftok': 5, 'flen': 14, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 42, 'bzhtok': 1, '《》': True},
 {'str': '勇悍', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 18, 'blen': 28, 'titlen': 35, 'bzhtok': 4, '《》': True},
 {'str': '‧', 'tag': 'Po', 'ftok': 3, 'flen': 7, 'slen': 1, 'stopword': False, 'name': False, 'btok': 17, 'blen': 27, 'titlen': 35, '《》': True},
 {'str': '17', 'tag': 'Nd', 'ftok': 4, 'flen': 8, 'slen': 2, 'stopword': False, 'name': False, 'btok': 16, 'blen': 25, 'titlen': 35, '《》': True},
 {'str': '困獸', 'tag': 'Lo', 'ftok': 7, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 13, 'blen': 21, 'titlen': 35, 'bzhtok': 3, '《》': True},
 {'str': '‧', 'tag': 'Po', 'ftok': 8, 'flen': 14, 'slen': 1, 'stopword': False, 'name': False, 'btok': 12, 'blen': 20, 'titlen': 35, '《》': True},
 {'str': '28', 'tag': 'Nd', 'ftok': 9, 'flen': 15, 'slen': 2, 'stopword': False, 'name': False, 'btok': 11, 'blen': 18, 'titlen': 35, '《》': True},
 {'str': '暴烈', 'tag': 'Lo', 'ftok': 12, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 8, 'blen': 14, 'titlen': 35, 'bzhtok': 2, '《》': True},
 {'str': '・', 'tag': 'Po', 'ftok': 13, 'flen': 21, 'slen': 1, 'stopword': False, 'name': False, 'btok': 7, 'blen': 13, 'titlen': 35, '《》': True},
 {'str': '34', 'tag': 'Nd', 'ftok': 14, 'flen': 22, 'slen': 2, 'stopword': False, 'name': False, 'btok': 6, 'blen': 11, 'titlen': 35, '《》': True},
 {'str': '假如讓你吻下去', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 0, 'blen': 0, 'titlen': 7, 'bzhtok': 1},
 {'str': '完全變態', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 42, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '懷很舊的舊', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 18, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '靜音模式', 'tag': 'Lo', 'ftok': 11, 'flen': 23, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 4, 'blen': 24, 'titlen': 51, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 12, 'flen': 27, 'slen': 1, 'stopword': False, 'name': False, 'btok': 3, 'blen': 23, 'titlen': 51, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': 'SILENT MODE', 'tag': 'Lstr', 'ftok': 13, 'flen': 28, 'slen': 11, 'stopword': False, 'name': False, 'btok': 2, 'blen': 12, 'titlen': 51, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '絕望元年', 'tag': 'Lo', 'ftok': 9, 'flen': 13, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 3, 'blen': 22, 'titlen': 39, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '初老', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 4, 'blen': 27, 'titlen': 29, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True},
 {'str': '百年樹木', 'tag': 'Lo', 'ftok': 7, 'flen': 21, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 10, 'titlen': 35, 'bzhtok': 1, '《》': True, '【】': False},
 {'str': '天若有情', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 11, 'blen': 34, 'titlen': 55, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True},
 {'str': '追夢人', 'tag': 'Lo', 'ftok': 17, 'flen': 52, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 5, 'btok': 0, 'blen': 0, 'titlen': 55, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '思覺失調', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 8, 'bzhtok': 1},
 {'str': '勇悍', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 14, 'blen': 25, 'titlen': 28, 'bzhtok': 4, '《》': True},
 {'str': '‧', 'tag': 'Po', 'ftok': 2, 'flen': 3, 'slen': 1, 'stopword': False, 'name': False, 'btok': 13, 'blen': 24, 'titlen': 28, '《》': True},
 {'str': '17', 'tag': 'Nd', 'ftok': 3, 'flen': 4, 'slen': 2, 'stopword': False, 'name': False, 'btok': 12, 'blen': 22, 'titlen': 28, '《》': True},
 {'str': '困獸', 'tag': 'Lo', 'ftok': 6, 'flen': 8, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 18, 'titlen': 28, 'bzhtok': 3, '《》': True},
 {'str': '‧', 'tag': 'Po', 'ftok': 7, 'flen': 10, 'slen': 1, 'stopword': False, 'name': False, 'btok': 8, 'blen': 17, 'titlen': 28, '《》': True},
 {'str': '28', 'tag': 'Nd', 'ftok': 8, 'flen': 11, 'slen': 2, 'stopword': False, 'name': False, 'btok': 7, 'blen': 15, 'titlen': 28, '《》': True},
 {'str': '化蝶', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 10, 'titlen': 12, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '子華說', 'tag': 'Lo', 'ftok': 7, 'flen': 21, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 4, 'blen': 14, 'titlen': 38, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '亂世情侶', 'tag': 'Lo', 'ftok': 4, 'flen': 11, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 48, 'titlen': 63, 'bzhtok': 3, '()': False, '[]': False, '《》': True},
 {'str': '太空艙', 'tag': 'Lo', 'ftok': 4, 'flen': 11, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 30, 'titlen': 44, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '亂世情侶', 'tag': 'Lo', 'ftok': 10, 'flen': 26, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 11, 'blen': 45, 'titlen': 75, 'bzhtok': 2, '()': False, '[]': False, '《》': False},
 {'str': '愛得太遲', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 9, 'titlen': 19, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '只是太愛你', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 7, 'blen': 15, 'titlen': 20, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '可一可再', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 10, 'blen': 51, 'titlen': 56, 'bzhtok': 2, '[]': False, '《》': True},
 {'str': '你的你', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 11, 'titlen': 29, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '[]': False, '《》': True},
 {'str': '傷心到變形', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 40, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '凱旋門', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 38, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '劇透', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '和懷念講再見', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 41, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '大女人主義', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 13, 'blen': 32, 'titlen': 52, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '孝順', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 37, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '小句號', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 38, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '演員', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 37, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '百姓', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 36, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '神不守舍', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 38, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '天下烏鴉', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 21, 'blen': 50, 'titlen': 66, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False, '《》': True},
 {'str': '那怕最終一個人', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '我記得', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 25, 'titlen': 40, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '日月存亡', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 27, 'titlen': 43, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '暗中愛我', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 29, 'titlen': 45, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '今夜煙花燦爛', 'tag': 'Lo', 'ftok': 7, 'flen': 24, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 4, 'blen': 23, 'titlen': 53, 'bzhtok': 1, '()': False, '《》': True},
 {'str': '告白', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 1, 'blen': 2, 'titlen': 18, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '愛徹底', 'tag': 'Lo', 'ftok': 7, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 32, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '歸宿', 'tag': 'Lo', 'ftok': 6, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 3, 'titlen': 24, 'bzhtok': 1, '《》': True},
 {'str': '我本人', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 10, 'bzhtok': 1, '《》': True},
 {'str': '還記得', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 38, 'titlen': 58, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '乒乓', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 26, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '背後女人', 'tag': 'Lo', 'ftok': 12, 'flen': 25, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 21, 'titlen': 50, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '男人背後', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '男人背後', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '老少平安', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '廢中', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 14, 'titlen': 20, 'bzhtok': 3, '《》': True, '（）': False},
 {'str': '誰還未覺醒', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 9, 'bzhtok': 1},
 {'str': '愛的故事沒有下集', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 44, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '守口如瓶', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 14, 'blen': 51, 'titlen': 56, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '【】': True},
 {'str': '守口如瓶', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 23, 'blen': 66, 'titlen': 71, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, '【】': True},
 {'str': '三年守望', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 20, 'blen': 60, 'titlen': 71, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False, '【】': False},
 {'str': '續集', 'tag': 'Lo', 'ftok': 6, 'flen': 13, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 15, 'blen': 28, 'titlen': 43, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': 'I', 'tag': 'Lu', 'ftok': 6, 'flen': 10, 'slen': 1, 'stopword': False, 'name': False, 'btok': 12, 'blen': 27, 'titlen': 38, 'dashbefore': False, 'dashafter': True, '[]': False, "''": False},
 {'str': "'", 'tag': 'Po', 'ftok': 7, 'flen': 11, 'slen': 1, 'stopword': False, 'name': False, 'btok': 11, 'blen': 26, 'titlen': 38, 'dashbefore': False, 'dashafter': True, '[]': False, "''": False},
 {'str': 'll Be There', 'tag': 'Lstr', 'ftok': 8, 'flen': 12, 'slen': 11, 'stopword': False, 'name': False, 'btok': 10, 'blen': 15, 'titlen': 38, 'dashbefore': False, 'dashafter': True, '[]': False, "''": False},
 {'str': '告別我的戀人們', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 13, 'titlen': 30, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '宮若梅', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 16, 'titlen': 29, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '實屬巧合', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 18, 'titlen': 32, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '幸福歌', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 14, 'blen': 32, 'titlen': 45, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '念念不忘', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 15, 'titlen': 29, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '意想不到', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 18, 'titlen': 32, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '愛我請留言', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 18, 'titlen': 33, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '投降吧', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 17, 'titlen': 30, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '最幸福的事', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 17, 'titlen': 32, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '此時此刻', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 17, 'titlen': 31, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '歲月如歌', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 17, 'titlen': 31, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '流淚行勝利道', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 15, 'titlen': 31, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '羅生門', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 11, 'blen': 28, 'titlen': 41, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '美好的時光', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 15, 'titlen': 30, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '小故事', 'tag': 'Lo', 'ftok': 10, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 12, 'blen': 21, 'titlen': 39, 'bzhtok': 5, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '所謂理想', 'tag': 'Lo', 'ftok': 10, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 10, 'blen': 16, 'titlen': 35, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '耿耿於懷', 'tag': 'Lo', 'ftok': 10, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 15, 'titlen': 34, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '護航', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 17, 'titlen': 29, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '遺物', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 17, 'titlen': 29, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '青春頌', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 17, 'titlen': 30, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '()': False, '[]': False},
 {'str': '年少無知', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 21, 'titlen': 41, 'bzhtok': 6, 'dashbefore': False, 'dashafter': True, '[]': False},
 {'str': '家明', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 7, 'blen': 39, 'titlen': 42, 'bzhtok': 2, '《》': True},
 {'str': '一種永遠', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 11, 'titlen': 29, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '勇氣情歌', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 33, 'titlen': 51, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '心之科學', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 32, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '花千樹', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 31, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '鏡子說', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 13, 'blen': 29, 'titlen': 46, 'bzhtok': 2, '()': False, '[]': False, '《》': True, '“”': False},
 {'str': '天窗', 'tag': 'Lo', 'ftok': 5, 'flen': 9, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 9, 'blen': 43, 'titlen': 54, 'bzhtok': 3, '《》': True},
 {'str': '公開道歉', 'tag': 'Lo', 'ftok': 5, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '仙樂處處飄', 'tag': 'Lo', 'ftok': 9, 'flen': 17, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 36, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '哪兒', 'tag': 'Lo', 'ftok': 9, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '小太陽', 'tag': 'Lo', 'ftok': 9, 'flen': 17, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 34, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '生命有價', 'tag': 'Lo', 'ftok': 9, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '睡前服', 'tag': 'Lo', 'ftok': 2, 'flen': 3, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 15, 'titlen': 21, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True},
 {'str': '睡前服', 'tag': 'Lo', 'ftok': 11, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 0, 'blen': 0, 'titlen': 21, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '一秒', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 14, 'titlen': 32, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False},
 {'str': '盡力呼吸', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 15, 'titlen': 33, 'bzhtok': 2, '《》': True},
 {'str': '經得起變化', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 34, 'titlen': 53, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '追', 'tag': 'Lo', 'ftok': 4, 'flen': 18, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 27, 'titlen': 46, 'bzhtok': 1, '【】': True},
 {'str': '追', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 5, 'titlen': 10, 'bzhtok': 2, '（）': False},
 {'str': '妳的名字', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 20, 'titlen': 30, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 5, 'flen': 10, 'slen': 1, 'stopword': False, 'name': False, 'btok': 7, 'blen': 19, 'titlen': 30, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '我的姓氏', 'tag': 'Lo', 'ftok': 6, 'flen': 11, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 15, 'titlen': 30, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '愛是永恒', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 16, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '李香蘭', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 3, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 15, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '追', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 13, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '垃圾', 'tag': 'Lo', 'ftok': 10, 'flen': 27, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 39, 'titlen': 68, 'bzhtok': 4, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '絕', 'tag': 'Lo', 'ftok': 12, 'flen': 30, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 10, 'blen': 37, 'titlen': 68, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '失樂園', 'tag': 'Lo', 'ftok': 14, 'flen': 32, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 8, 'blen': 33, 'titlen': 68, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '大開眼戒', 'tag': 'Lo', 'ftok': 16, 'flen': 36, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 5, 'btok': 6, 'blen': 28, 'titlen': 68, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '下次愛你', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 34, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '囍帖街', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '塵埃落定', 'tag': 'Lo', 'ftok': 7, 'flen': 19, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '天才兒童', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 15, 'titlen': 35, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '1985', 'tag': 'Nd', 'ftok': 5, 'flen': 20, 'slen': 4, 'stopword': False, 'name': False, 'btok': 4, 'blen': 11, 'titlen': 35, '[]': False, '《》': True},
 {'str': '天才兒童', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 11, 'blen': 33, 'titlen': 53, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '1985', 'tag': 'Nd', 'ftok': 5, 'flen': 20, 'slen': 4, 'stopword': False, 'name': False, 'btok': 10, 'blen': 29, 'titlen': 53, '()': False, '[]': False, '《》': True},
 {'str': '完全因你', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 37, 'titlen': 59, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '少女的祈禱', 'tag': 'Lo', 'ftok': 8, 'flen': 23, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 8, 'blen': 31, 'titlen': 59, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '夜機', 'tag': 'Lo', 'ftok': 10, 'flen': 29, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 6, 'blen': 28, 'titlen': 59, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '天窗', 'tag': 'Lo', 'ftok': 12, 'flen': 34, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 28, 'titlen': 64, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '預言書', 'tag': 'Lo', 'ftok': 10, 'flen': 26, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 4, 'blen': 9, 'titlen': 38, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True},
 {'str': '笑忘書', 'tag': 'Lo', 'ftok': 12, 'flen': 30, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 2, 'blen': 5, 'titlen': 38, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '青春常駐', 'tag': 'Lo', 'ftok': 14, 'flen': 34, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 5, 'btok': 0, 'blen': 0, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '我的天', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 49, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '披星戴月', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 50, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '明明他已離開妳', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 11, 'titlen': 34, 'bzhtok': 1, '《》': True},
 {'str': '春秋', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 48, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '歲月靜好', 'tag': 'Lo', 'ftok': 5, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 11, 'titlen': 32, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '潛水', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 23, 'titlen': 41, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '井', 'tag': 'Lo', 'ftok': 16, 'flen': 44, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 8, 'blen': 31, 'titlen': 76, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '留白', 'tag': 'Lo', 'ftok': 18, 'flen': 46, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 6, 'blen': 28, 'titlen': 76, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '手望', 'tag': 'Lo', 'ftok': 12, 'flen': 35, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 28, 'titlen': 65, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '百年樹木', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 11, 'titlen': 31, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '百年樹木', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 34, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '空手而來', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 29, 'titlen': 49, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '笑忘書', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 49, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '缺', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 31, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '老了十歲', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 50, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '裝睡的情人', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 11, 'titlen': 32, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '追風箏的孩子', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 52, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '遙吻', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 48, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '酷愛', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 48, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '餘震', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 48, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '騷靈情歌', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 28, 'titlen': 50, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '黃色大門', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 34, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': 'HURT SO BAD', 'tag': 'Lstr', 'ftok': 6, 'flen': 22, 'slen': 11, 'stopword': False, 'name': False, 'btok': 0, 'blen': 0, 'titlen': 33},
 {'str': '不吐不快', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 0, 'blen': 0, 'titlen': 26, 'bzhtok': 1},
 {'str': '櫻花樹下', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 0, 'blen': 0, 'titlen': 26, 'bzhtok': 1},
 {'str': '預言書', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 0, 'blen': 0, 'titlen': 25, 'bzhtok': 1},
 {'str': '春秋', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 5, 'titlen': 11, 'bzhtok': 1},
 {'str': '襯', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 7, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '封箱', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '盟誓', 'tag': 'Lo', 'ftok': 7, 'flen': 10, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 23, 'titlen': 35, 'bzhtok': 3, '《》': False, '【】': True},
 {'str': '情感的廢墟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 4, 'blen': 13, 'titlen': 18, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '情感的廢墟', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 14, 'titlen': 19, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True},
 {'str': '偷情的禮儀', 'tag': 'Lo', 'ftok': 4, 'flen': 10, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 4, 'titlen': 19, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '我們萬歲', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 10, 'blen': 57, 'titlen': 62, 'bzhtok': 2, '[]': False, '《》': True},
 {'str': '細看近年', 'tag': 'Lo', 'ftok': 6, 'flen': 11, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 16, 'titlen': 31, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False},
 {'str': '，', 'tag': 'Po', 'ftok': 7, 'flen': 15, 'slen': 1, 'stopword': False, 'name': False, 'btok': 3, 'blen': 15, 'titlen': 31, 'dashbefore': True, 'dashafter': False},
 {'str': '那信念', 'tag': 'Lo', 'ftok': 8, 'flen': 16, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 12, 'titlen': 31, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '雞蛋與羔羊', 'tag': 'Lo', 'ftok': 8, 'flen': 19, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 5, 'blen': 12, 'titlen': 36, 'bzhtok': 1, '()': False, '[]': False, '【】': True},
 {'str': '給傷心', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 5, 'titlen': 17, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '你是你本身的傳奇', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '假使世界原來不像你預期', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 11, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 40, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '分手總約在雨天', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 36, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '時間囊', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 32, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '願', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 30, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '存在', 'tag': 'Lo', 'ftok': 4, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 23, 'titlen': 44, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '我我', 'tag': 'Lo', 'ftok': 4, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 11, 'titlen': 32, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '永生花', 'tag': 'Lo', 'ftok': 4, 'flen': 19, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 36, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '青春', 'tag': 'Lo', 'ftok': 5, 'flen': 20, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 14, 'blen': 54, 'titlen': 76, 'bzhtok': 2, '()': False, '[]': False, '《》': True},
 {'str': '、', 'tag': 'Po', 'ftok': 6, 'flen': 22, 'slen': 1, 'stopword': False, 'name': False, 'btok': 13, 'blen': 53, 'titlen': 76, '()': False, '[]': False, '《》': True},
 {'str': '戀愛和意外', 'tag': 'Lo', 'ftok': 7, 'flen': 23, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 12, 'blen': 48, 'titlen': 76, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '單身狗', 'tag': 'Lo', 'ftok': 4, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 32, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '講感情', 'tag': 'Lo', 'ftok': 5, 'flen': 14, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 24, 'titlen': 41, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 6, 'flen': 17, 'slen': 1, 'stopword': False, 'name': False, 'btok': 7, 'blen': 23, 'titlen': 41, 'dashbefore': True, 'dashafter': True},
 {'str': '傷感情', 'tag': 'Lo', 'ftok': 7, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 20, 'titlen': 41, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '第三顆行星', 'tag': 'Lo', 'ftok': 4, 'flen': 14, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '愛情是一種法國甜品', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 24, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '有淚多好', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '難得一遇', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '高山低谷', 'tag': 'Lo', 'ftok': 6, 'flen': 11, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 10, 'titlen': 25, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '有了你', 'tag': 'Lo', 'ftok': 7, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 17, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': 'just carry on', 'tag': 'Lstr', 'ftok': 5, 'flen': 17, 'slen': 13, 'stopword': False, 'name': False, 'btok': 4, 'blen': 23, 'titlen': 53, '()': False, '《》': True},
 {'str': '下一位前度', 'tag': 'Lo', 'ftok': 4, 'flen': 16, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 33, 'titlen': 54, 'bzhtok': 1, '()': False, '《》': True},
 {'str': '下一位前度', 'tag': 'Lo', 'ftok': 5, 'flen': 17, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 29, 'titlen': 51, 'bzhtok': 1, '()': False, '《》': True},
 {'str': '假如讓你吻下去', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 13, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': 'Da Di Da', 'tag': 'Lstr', 'ftok': 6, 'flen': 14, 'slen': 8, 'stopword': False, 'name': False, 'btok': 4, 'blen': 23, 'titlen': 45, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '哪裡只得我共你', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 44, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '玫瑰式體驗', 'tag': 'Lo', 'ftok': 5, 'flen': 13, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 44, 'titlen': 62, 'bzhtok': 1, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '忍', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 24, 'titlen': 29, 'bzhtok': 1, '()': False},
 {'str': '重光紀念日', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 24, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '努力奮鬥加油', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 31, 'titlen': 52, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '我今朝有啲唔舒服', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 15, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '忽然又想起你', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 30, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '再見灰姑娘', 'tag': 'Lo', 'ftok': 7, 'flen': 18, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 26, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '問題青年', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 40, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '月亮不代表我的心', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 44, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '閃亮的青春', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '10', 'tag': 'Nd', 'ftok': 2, 'flen': 4, 'slen': 2, 'stopword': False, 'name': False, 'btok': 12, 'blen': 42, 'titlen': 48, '[]': False},
 {'str': '。', 'tag': 'Po', 'ftok': 3, 'flen': 6, 'slen': 1, 'stopword': False, 'name': False, 'btok': 11, 'blen': 41, 'titlen': 48, '[]': False},
 {'str': '思念', 'tag': 'Lo', 'ftok': 4, 'flen': 7, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 39, 'titlen': 48, 'bzhtok': 3, '[]': False},
 {'str': '。', 'tag': 'Po', 'ftok': 5, 'flen': 9, 'slen': 1, 'stopword': False, 'name': False, 'btok': 9, 'blen': 38, 'titlen': 48, '[]': False},
 {'str': '音樂', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 8, 'blen': 36, 'titlen': 48, 'bzhtok': 2, '[]': False},
 {'str': '。', 'tag': 'Po', 'ftok': 7, 'flen': 12, 'slen': 1, 'stopword': False, 'name': False, 'btok': 7, 'blen': 35, 'titlen': 48, '[]': False},
 {'str': '會', 'tag': 'Lo', 'ftok': 8, 'flen': 13, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 6, 'blen': 34, 'titlen': 48, 'bzhtok': 1, '[]': False},
 {'str': '相思河畔', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 8, 'bzhtok': 1},
 {'str': '一二三', 'tag': 'Lo', 'ftok': 6, 'flen': 19, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 25, 'titlen': 47, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '，', 'tag': 'Po', 'ftok': 7, 'flen': 22, 'slen': 1, 'stopword': False, 'name': False, 'btok': 9, 'blen': 24, 'titlen': 47, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '三二一', 'tag': 'Lo', 'ftok': 8, 'flen': 23, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 8, 'blen': 21, 'titlen': 47, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '愛的森林', 'tag': 'Lo', 'ftok': 5, 'flen': 11, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 13, 'titlen': 28, 'bzhtok': 1, '[]': True},
 {'str': '極夜後', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 11, 'blen': 31, 'titlen': 35, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '《》': True, '“”': False, "''": False},
 {'str': '橡筋', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 14, 'blen': 34, 'titlen': 37, 'bzhtok': 3, 'dashbefore': False, 'dashafter': True, '()': False, '【】': True},
 {'str': '櫻花樹下', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 6, 'blen': 11, 'titlen': 15, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '一天一天等下去', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 46, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '今生不再', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 27, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '今生今世', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 27, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '天若有情', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 27, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '騎膊馬', 'tag': 'Lo', 'ftok': 4, 'flen': 9, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 26, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '彌敦道', 'tag': 'Lo', 'ftok': 4, 'flen': 13, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 30, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '數寄屋橋次郎', 'tag': 'Lo', 'ftok': 4, 'flen': 13, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 30, 'titlen': 49, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '相識以後', 'tag': 'Lo', 'ftok': 4, 'flen': 13, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 31, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '週日司機', 'tag': 'Lo', 'ftok': 4, 'flen': 13, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 31, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '十號儲物櫃', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 38, 'titlen': 59, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '好奇殺死愛', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 34, 'titlen': 55, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '打死不離歌星夢', 'tag': 'Lo', 'ftok': 8, 'flen': 28, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 5, 'btok': 2, 'blen': 6, 'titlen': 41, 'bzhtok': 2, '《》': True},
 {'str': '漁舟唱晚', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 4, 'blen': 6, 'titlen': 10, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True},
 {'str': '原來她不夠愛我', 'tag': 'Lo', 'ftok': 10, 'flen': 22, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 20, 'titlen': 49, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '[]': False},
 {'str': '陽光點的歌', 'tag': 'Lo', 'ftok': 10, 'flen': 22, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 20, 'titlen': 47, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '[]': False},
 {'str': '花花草草', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 14, 'titlen': 35, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': '突然蒸發', 'tag': 'Lo', 'ftok': 0, 'flen': 0, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 11, 'blen': 16, 'titlen': 20, 'bzhtok': 4, 'dashbefore': False, 'dashafter': True, '()': False, "''": False},
 {'str': '自動棄權', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 14, 'blen': 19, 'titlen': 40, 'bzhtok': 5, 'dashbefore': True, 'dashafter': True, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 7, 'flen': 21, 'slen': 1, 'stopword': False, 'name': False, 'btok': 13, 'blen': 18, 'titlen': 40, 'dashbefore': True, 'dashafter': True, '《》': True},
 {'str': '-', 'tag': 'Pd', 'ftok': 8, 'flen': 22, 'slen': 1, 'stopword': False, 'name': False, 'btok': 12, 'blen': 17, 'titlen': 40, 'dashbefore': True, 'dashafter': True, '《》': True},
 {'str': ' ', 'tag': 'Zs', 'ftok': 9, 'flen': 23, 'slen': 1, 'stopword': False, 'name': False, 'btok': 11, 'blen': 16, 'titlen': 40, 'dashbefore': True, 'dashafter': True, '《》': True},
 {'str': '肥佬版', 'tag': 'Lo', 'ftok': 10, 'flen': 24, 'slen': 3, 'stopword': True, 'name': False, 'fzhtok': 3, 'btok': 10, 'blen': 13, 'titlen': 40, 'bzhtok': 4, 'dashbefore': True, 'dashafter': True, '《》': True},
 {'str': '謝謝你', 'tag': 'Lo', 'ftok': 7, 'flen': 19, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 24, 'titlen': 46, 'bzhtok': 3, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 8, 'flen': 22, 'slen': 1, 'stopword': False, 'name': False, 'btok': 7, 'blen': 23, 'titlen': 46, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '傷過我', 'tag': 'Lo', 'ftok': 9, 'flen': 23, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 20, 'titlen': 46, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True, '()': False},
 {'str': '可惜我是水瓶座', 'tag': 'Lo', 'ftok': 12, 'flen': 15, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 4, 'blen': 7, 'titlen': 29, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '自遊', 'tag': 'Lo', 'ftok': 3, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 37, 'bzhtok': 1, '()': False},
 {'str': '青玉案', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '半邊天', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 32, 'titlen': 47, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, '“”': False, "''": False},
 {'str': '偉業街', 'tag': 'Lo', 'ftok': 6, 'flen': 13, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '抱擁情人', 'tag': 'Lo', 'ftok': 6, 'flen': 13, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 38, 'titlen': 55, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '為愛冒險', 'tag': 'Lo', 'ftok': 6, 'flen': 13, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 29, 'titlen': 46, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '慢慢喜歡你', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 21, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '後來沒有你', 'tag': 'Lo', 'ftok': 4, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 32, 'bzhtok': 1, '《》': True},
 {'str': '那誰', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 24, 'bzhtok': 2, '《》': True},
 {'str': '獨行俠侶', 'tag': 'Lo', 'ftok': 10, 'flen': 29, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 3, 'blen': 5, 'titlen': 38, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '伯利恆的主角', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 45, 'titlen': 69, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '在月台上等你', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 43, 'titlen': 67, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '生涯規劃', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 32, 'titlen': 54, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '恐怖情人', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 37, 'titlen': 58, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '白紙', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 34, 'titlen': 53, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '教我這麼愛下去', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 43, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '逆流成河', 'tag': 'Lo', 'ftok': 4, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 34, 'titlen': 53, 'bzhtok': 1, '()': False, '[]': False, '《》': True},
 {'str': '你們的幸福', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 20, 'bzhtok': 1, '《》': True},
 {'str': '十倍奉還', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 13, 'titlen': 31, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '山林道', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 7, 'titlen': 22, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False, '（）': False},
 {'str': '我們都被忘了', 'tag': 'Lo', 'ftok': 5, 'flen': 13, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 10, 'titlen': 29, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '我可以被世界淘汰', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 23, 'titlen': 45, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '，', 'tag': 'Po', 'ftok': 7, 'flen': 22, 'slen': 1, 'stopword': False, 'name': False, 'btok': 5, 'blen': 22, 'titlen': 45, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '但不可以被世界擊敗', 'tag': 'Lo', 'ftok': 8, 'flen': 23, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 4, 'blen': 13, 'titlen': 45, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '最好的時刻', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 17, 'titlen': 36, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '雞蛋與羔羊', 'tag': 'Lo', 'ftok': 4, 'flen': 12, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 17, 'titlen': 34, 'bzhtok': 1, '()': False, '《》': True},
 {'str': '愁人節', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 9, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '我愛茶餐廳', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 11, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '沐春風', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 33, 'titlen': 42, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': 'Amazing Grace', 'tag': 'Lstr', 'ftok': 6, 'flen': 12, 'slen': 13, 'stopword': False, 'name': False, 'btok': 12, 'blen': 37, 'titlen': 62, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': 'Can You Hear', 'tag': 'Lstr', 'ftok': 6, 'flen': 12, 'slen': 12, 'stopword': False, 'name': False, 'btok': 12, 'blen': 27, 'titlen': 51, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': 'Lonely', 'tag': 'Lul', 'ftok': 6, 'flen': 12, 'slen': 6, 'stopword': False, 'name': False, 'btok': 12, 'blen': 26, 'titlen': 44, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '冰傷', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 26, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '怎麼你不找我', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 30, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '有了你', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 13, 'blen': 28, 'titlen': 43, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '不得了小姐', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 9, 'blen': 19, 'titlen': 39, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '黃金花', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 14, 'blen': 33, 'titlen': 53, 'bzhtok': 5, 'dashbefore': True, 'dashafter': True, '()': False, '《》': False},
 {'str': '你在聽嗎', 'tag': 'Lo', 'ftok': 5, 'flen': 9, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 22, 'titlen': 35, 'bzhtok': 1, '《》': True},
 {'str': '盡力呼吸', 'tag': 'Lo', 'ftok': 11, 'flen': 20, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 6, 'blen': 9, 'titlen': 33, 'bzhtok': 3, 'dashbefore': True, 'dashafter': False, '()': False, '《》': False},
 {'str': '難得咁人齊', 'tag': 'Lo', 'ftok': 4, 'flen': 5, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 8, 'blen': 22, 'titlen': 32, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '[]': False},
 {'str': '逆流之歌', 'tag': 'Lo', 'ftok': 7, 'flen': 28, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 11, 'blen': 27, 'titlen': 59, 'bzhtok': 3, '《》': False, '【】': True},
 {'str': '到此為止', 'tag': 'Lo', 'ftok': 6, 'flen': 16, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 31, 'titlen': 51, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '到此為止', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 31, 'titlen': 47, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '孤身走', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 12, 'blen': 28, 'titlen': 43, 'bzhtok': 4, 'dashbefore': True, 'dashafter': False, '()': False, "''": False},
 {'str': '回憶有罪', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 5, 'titlen': 14, 'bzhtok': 2, '《》': True},
 {'str': '石頭記', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 8, 'bzhtok': 1},
 {'str': '和好', 'tag': 'Lo', 'ftok': 6, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 44, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '重陽', 'tag': 'Lo', 'ftok': 6, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '雲吞', 'tag': 'Lo', 'ftok': 6, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 44, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '最佳演員', 'tag': 'Lo', 'ftok': 3, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 12, 'titlen': 31, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '藍鞋子', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 11, 'titlen': 32, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '電燈膽', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 12, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '他不准我哭', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 5, 'titlen': 16, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '愛是最大權利', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 12, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '無賴', 'tag': 'Lo', 'ftok': 5, 'flen': 7, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 11, 'titlen': 20, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '[]': True},
 {'str': '關於寂寞', 'tag': 'Lo', 'ftok': 5, 'flen': 7, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 32, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '黑彩虹', 'tag': 'Lo', 'ftok': 5, 'flen': 7, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 31, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '千年如一日', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '我們都是這樣長大的', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 40, 'titlen': 67, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '13', 'tag': 'Nd', 'ftok': 4, 'flen': 19, 'slen': 2, 'stopword': False, 'name': False, 'btok': 3, 'blen': 26, 'titlen': 47, '《》': True},
 {'str': '樓的大笨象', 'tag': 'Lo', 'ftok': 5, 'flen': 21, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 47, 'bzhtok': 1, '《》': True},
 {'str': '氪氣石', 'tag': 'Lo', 'ftok': 4, 'flen': 19, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 43, 'bzhtok': 1, '《》': True},
 {'str': '勾手指尾', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 3, 'titlen': 17, 'bzhtok': 1, '《》': True},
 {'str': '拖泥帶水', 'tag': 'Lo', 'ftok': 6, 'flen': 10, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 2, 'blen': 3, 'titlen': 17, 'bzhtok': 1, '《》': True},
 {'str': '阿牛', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 6, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '女神', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 2, 'stopword': False, 'name': True, 'fzhtok': 3, 'btok': 0, 'blen': 0, 'titlen': 24, 'bzhtok': 1},
 {'str': '我本人', 'tag': 'Lo', 'ftok': 6, 'flen': 22, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 0, 'blen': 0, 'titlen': 25, 'bzhtok': 1},
 {'str': '告別的藝術', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 42, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '在錯誤的宇宙尋找愛', 'tag': 'Lo', 'ftok': 6, 'flen': 14, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 46, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '一吻穿越四十六億歲', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '任我行', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 22, 'bzhtok': 1, '《》': True},
 {'str': '四季', 'tag': 'Lo', 'ftok': 7, 'flen': 18, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 34, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '富士山下', 'tag': 'Lo', 'ftok': 7, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 5, 'titlen': 27, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False, '《》': True},
 {'str': '我們', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 17, 'titlen': 35, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '漸漸', 'tag': 'Lo', 'ftok': 4, 'flen': 15, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 10, 'blen': 47, 'titlen': 64, 'bzhtok': 1, 'dashbefore': False, 'dashafter': True, '[]': False, '《》': True},
 {'str': '漸漸', 'tag': 'Lo', 'ftok': 5, 'flen': 16, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 19, 'blen': 53, 'titlen': 71, 'bzhtok': 2, 'dashbefore': False, 'dashafter': True, '[]': False, "''": True},
 {'str': '唯讀最好時刻', 'tag': 'Lo', 'ftok': 7, 'flen': 19, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 17, 'blen': 46, 'titlen': 71, 'bzhtok': 1, 'dashbefore': True, 'dashafter': True, '[]': False, "''": True},
 {'str': '無條件', 'tag': 'Lo', 'ftok': 7, 'flen': 18, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 24, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '人來人往', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 10, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '十面埋伏', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 16, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '明年今日', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 5, 'blen': 12, 'titlen': 22, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '苦瓜', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 9, 'bzhtok': 1, '【】': True},
 {'str': 'Be with you', 'tag': 'Lstr', 'ftok': 4, 'flen': 15, 'slen': 11, 'stopword': False, 'name': False, 'btok': 5, 'blen': 15, 'titlen': 41, '[]': False, '《》': True},
 {'str': '尾站天國', 'tag': 'Lo', 'ftok': 4, 'flen': 15, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 22, 'titlen': 41, 'bzhtok': 1, '[]': False, '《》': True},
 {'str': '別來無恙', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '別來無恙', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 35, 'titlen': 56, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '沒有你', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 3, 'blen': 8, 'titlen': 28, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False},
 {'str': ',', 'tag': 'Po', 'ftok': 7, 'flen': 20, 'slen': 1, 'stopword': False, 'name': False, 'btok': 2, 'blen': 7, 'titlen': 28, 'dashbefore': True, 'dashafter': False},
 {'str': ' ', 'tag': 'Zs', 'ftok': 8, 'flen': 21, 'slen': 1, 'stopword': False, 'name': False, 'btok': 1, 'blen': 6, 'titlen': 28, 'dashbefore': True, 'dashafter': False},
 {'str': '我甚麼都不是', 'tag': 'Lo', 'ftok': 9, 'flen': 22, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 0, 'blen': 0, 'titlen': 28, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '磚頭', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 19, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '航拍', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '認真如初', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '逸後', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 19, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '金草莓', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 15, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '霸氣情歌', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 35, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '尊嚴', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 0, 'blen': 0, 'titlen': 8, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False},
 {'str': '凝望', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 14, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '初戀', 'tag': 'Lo', 'ftok': 4, 'flen': 6, 'slen': 2, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 6, 'titlen': 14, 'bzhtok': 2, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '當我迷失時聽著的歌', 'tag': 'Lo', 'ftok': 5, 'flen': 17, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 21, 'titlen': 47, 'bzhtok': 1, '《》': True},
 {'str': '飲啦小氣', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 30, 'titlen': 52, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '我們的航海時代', 'tag': 'Lo', 'ftok': 2, 'flen': 5, 'slen': 7, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 1, 'blen': 1, 'titlen': 13, 'bzhtok': 1, '《》': True},
 {'str': '沒有人是孤島', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 6, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 38, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '山旮旯', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '終生女友', 'tag': 'Lo', 'ftok': 7, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 2, 'blen': 3, 'titlen': 24, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '《》': True},
 {'str': '羅生門', 'tag': 'Lo', 'ftok': 8, 'flen': 19, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 10, 'blen': 36, 'titlen': 58, 'bzhtok': 3, '[]': False, '《》': True},
 {'str': '耿耿於懷', 'tag': 'Lo', 'ftok': 7, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 3, 'btok': 19, 'blen': 34, 'titlen': 52, 'bzhtok': 6, '()': True, '《》': True, '（）': True},
 {'str': '念念不忘', 'tag': 'Lo', 'ftok': 11, 'flen': 21, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 15, 'blen': 27, 'titlen': 52, 'bzhtok': 5, '()': True, '《》': True, '（）': True},
 {'str': '羅生門', 'tag': 'Lo', 'ftok': 15, 'flen': 28, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 6, 'btok': 11, 'blen': 21, 'titlen': 52, 'bzhtok': 3, '()': True, '《》': True, '（）': True},
 {'str': '寂寞就如', 'tag': 'Lo', 'ftok': 2, 'flen': 4, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 7, 'blen': 15, 'titlen': 23, 'bzhtok': 4, '《》': True},
 {'str': '其實寂寞', 'tag': 'Lo', 'ftok': 7, 'flen': 14, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 2, 'blen': 5, 'titlen': 23, 'bzhtok': 2, '《》': True},
 {'str': '金剛圈', 'tag': 'Lo', 'ftok': 3, 'flen': 5, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 1, 'blen': 1, 'titlen': 9, 'bzhtok': 1, '《》': True},
 {'str': '如何從夏天活過來', 'tag': 'Lo', 'ftok': 6, 'flen': 15, 'slen': 8, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': 'Dream My Dreams', 'tag': 'Lstr', 'ftok': 6, 'flen': 18, 'slen': 15, 'stopword': False, 'name': False, 'btok': 4, 'blen': 14, 'titlen': 47, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '一定要得', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 45, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '光引致疼痛', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 37, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '如果青春不會有盡頭', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 9, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 41, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '很久不見', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 23, 'titlen': 45, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '問誰未發聲', 'tag': 'Lo', 'ftok': 6, 'flen': 12, 'slen': 5, 'stopword': False, 'name': False, 'fzhtok': 4, 'btok': 0, 'blen': 0, 'titlen': 17, 'bzhtok': 1},
 {'str': '怕', 'tag': 'Lo', 'ftok': 6, 'flen': 18, 'slen': 1, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 4, 'blen': 14, 'titlen': 33, 'bzhtok': 1, 'dashbefore': True, 'dashafter': False, '()': False},
 {'str': '剩下光年', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 26, 'titlen': 47, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '剩下光年', 'tag': 'Lo', 'ftok': 6, 'flen': 17, 'slen': 4, 'stopword': False, 'name': False, 'fzhtok': 2, 'btok': 6, 'blen': 20, 'titlen': 41, 'bzhtok': 2, 'dashbefore': True, 'dashafter': True},
 {'str': '龍舌蘭', 'tag': 'Lo', 'ftok': 1, 'flen': 1, 'slen': 3, 'stopword': False, 'name': False, 'fzhtok': 1, 'btok': 10, 'blen': 49, 'titlen': 53, 'bzhtok': 2, '[]': False, '《》': True},
]
